### ISSUE TITLE
update scalameta and scalafix version

### ISSUE THREAD

**Issue by xuwei-k** [xuwei-k/unused-code#5]
```
compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:938: error: error in interpolated string: identifier, `this' or block expected
[error]     debug.println(i"checking redundancy in $_match")
[error]                                             ^
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.ScalametaParser.unquoteExpr(ScalametaParser.scala:2316)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$interpolateTerm$1(ScalametaParser.scala:2233)
```

**Comment by xuwei-k** [comment]
- https://github.com/xuwei-k/unused-code/pull/17
